name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup .NET SDK
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Build the project
      - name: Build the project
        run: dotnet build --no-restore --configuration Release
      
      # Run tests
      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
